### ISSUE TITLE
Upozornit studenta, k jakému cvičícímu nahrává projekt

### ISSUE THREAD

**Issue by IndyB961E** [pavlosweb/slfjaeal#24]
Nechal bych v nabídce s učitelem předvybranou nějakou hodnotu "none", aby si student vybral, ke komu nechává projekt opravit.

**Comment by pavlosweb** [comment]
Vyřešil jsem to přesně tak, před uploadem musí zvolit cviíčícího, jinak nemůžu uploadovat.
