### ISSUE TITLE
Změna statusu, obnovení zobrazení aktuální revize

### ISSUE THREAD

**Issue by IndyB961E** [pavlosweb/slfjaeal#28]
Při shlédnutí, vrácení k dopracování nebo uzavření se neaktualizuje zobrazení aktuální revize, tzn. u revize se zobrazuje původní status a nezmění se dostupnost tlačítek "Shlédnuto", "Vrátit", "Dokončit", atd.

**Comment by pavlosweb** [comment]
mělo by být opraveno v nové verzi
