### ISSUE TITLE
Problém s označováním shlédnutých revizí

### ISSUE THREAD

**Issue by IndyB961E** [pavlosweb/slfjaeal#32]
1.	Student – Nahrán úkol „Zadání a analýzy“ ve formátu PDF.
2.	Student – Nahrán úkol „ORM“ ve formátu ZIP.
6.	Student – Nahrána další revize „Zadání a analýzy“
7.	Teacher – Shlédnuta revize 3
8.	Teacher – Dokončena revize 3
9.	Teacher – Obnovena revize 3
10.	Teacher – Revize 3 se označuje symbolem „*“, přestože byla shlédnuta.

I když kliknu na "Shlédnout", revize se pořád zobrazuje jako "NEW".

**Comment by pavlosweb** [comment]
opraveno v nové verzi
